# -*- coding: utf-8 -*-
"""EAI6010_Assignment6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FlbnqLtX4jL9faHai92tNBazH0i5fqqd
"""

import streamlit as st
import pandas as pd
import spacy
from textblob import TextBlob

# Load spaCy model (assumes it's preinstalled)
try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    st.error("Error: spaCy model 'en_core_web_sm' is missing. Ensure it is installed in requirements.txt.")

# Streamlit App
st.title("Airbnb Listing NLP Analyzer")

# File uploader
uploaded_file = st.file_uploader("Upload Airbnb Listings CSV", type=["csv", "gz"])

if uploaded_file:
    if uploaded_file.name.endswith('.gz'):
        df = pd.read_csv(uploaded_file, compression='gzip')
    else:
        df = pd.read_csv(uploaded_file)

    if "description" in df.columns:
        text_column = "description"
    else:
        text_column = st.selectbox("Select the column with property descriptions", df.columns)

    # Process descriptions
    if st.button("Analyze Descriptions"):
        entity_results = []
        sentiment_results = []

        for text in df[text_column].dropna():
            doc = nlp(text)
            entities = [(ent.text, ent.label_) for ent in doc.ents]
            sentiment = TextBlob(text).sentiment.polarity

            entity_results.append(entities)
            sentiment_results.append(sentiment)

        df["Entities"] = entity_results
        df["Sentiment"] = sentiment_results

        st.write("### Processed Data:")
        st.dataframe(df[["description", "Entities", "Sentiment"]])

        csv_data = df.to_csv(index=False).encode('utf-8')
        st.download_button("Download Processed Data", csv_data, "airbnb_nlp_results.csv", "text/csv")

st.write("Upload an Airbnb dataset with textual property descriptions to analyze entities and sentiment!")
